int printf(char *s, ...);

const ci;
int const ci;
const int ci;
signed const ci;
const signed ci;
signed int const ci;
signed const int ci;
const signed int ci;
int signed const ci;
int const signed ci;
const int signed ci;
unsigned const cui;
const unsigned cui;
unsigned int const cui;
unsigned const int cui;
const unsigned int cui;
int unsigned const cui;
int const unsigned cui;
const int unsigned cui;
volatile vi;
int volatile vi;
volatile int vi;
signed volatile vi;
volatile signed vi;
signed int volatile vi;
signed volatile int vi;
volatile signed int vi;
int signed volatile vi;
int volatile signed vi;
volatile int signed vi;
unsigned volatile vui;
volatile unsigned vui;
unsigned int volatile vui;
unsigned volatile int vui;
volatile unsigned int vui;
int unsigned volatile vui;
int volatile unsigned vui;
volatile int unsigned vui;
const volatile cvi;
volatile const cvi;
int const volatile cvi;
int volatile const cvi;
const int volatile cvi;
const volatile int cvi;
volatile int const cvi;
volatile const int cvi;
signed const volatile cvi;
signed volatile const cvi;
const signed volatile cvi;
const volatile signed cvi;
volatile signed const cvi;
volatile const signed cvi;
unsigned const volatile cvui;
unsigned volatile const cvui;
const unsigned volatile cvui;
const volatile unsigned cvui;
volatile unsigned const cvui;
volatile const unsigned cvui;

int main() {
  printf("Compatible type test\n");
  return 0;
}
