int printf(char *s, ...);

short s;
int i;
long l;
long long ll;
signed i;
unsigned ui;
signed char sc;
char signed sc;
signed short s;
short signed s;
signed int i;
int signed i;
signed long l;
long signed l;
signed long long ll;
long signed long ll;
long long signed ll;
unsigned char uc;
char unsigned uc;
unsigned short us;
short unsigned us;
unsigned int ui;
int unsigned ui;
unsigned long ul;
long unsigned ul;
unsigned long long ull;
long long unsigned ull;
long unsigned long ull;
short int s;
int short s;
long int l;
int long l;
long long int ll;
long int long ll;
int long long ll;
long double ld;
double long ld;
signed short int s;
signed int short s;
short signed int s;
short int signed s;
int signed short s;
int short signed s;
signed long int l;
signed int long l;
long signed int l;
long int signed l;
int signed long l;
int long signed l;
signed long long int ll;
signed long int long ll;
signed int long long ll;
long signed long int ll;
long signed int long ll;
long long signed int ll;
long long int signed ll;
long int signed long ll;
long int long signed ll;
int signed long long ll;
int long signed long ll;
int long long signed ll;
unsigned short int us;
unsigned int short us;
short unsigned int us;
short int unsigned us;
int unsigned short us;
int short unsigned us;
unsigned long int ul;
unsigned int long ul;
long unsigned int ul;
long int unsigned ul;
int unsigned long ul;
int long unsigned ul;
unsigned long long int ull;
unsigned long int long ull;
unsigned int long long ull;
long unsigned long int ull;
long unsigned int long ull;
long long unsigned int ull;
long long int unsigned ull;
long int unsigned long ull;
long int long unsigned ull;
int unsigned long long ull;
int long unsigned long ull;
int long long unsigned ull;

int main() {
  printf("Compatible type test\n");
  return 0;
}
