/*
 *  This software may only be used by you under license from AT&T Corp.
 *  ("AT&T").  A copy of AT&T's Source Code Agreement is available at
 *  AT&T's Internet website having the URL:
 *  <http://www.research.att.com/sw/tools/graphviz/license/source.html>
 *  If you received this software without first entering into a license
 *  with AT&T, you have an infringing copy of this software and cannot use
 *  it without violating AT&T's intellectual property rights.
 */

//----------------------------------------------------
// The following code was generated by CUP v0.9e
// Fri Jan 09 14:17:55 EST 1998
//----------------------------------------------------

package att.grappa;

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SEMI = 10;
  static final int EDGE = 6;
  static final int ND_EDGE_OP = 8;
  static final int EOF = 0;
  static final int COLON = 17;
  static final int EQUAL = 16;
  static final int GRAPH = 2;
  static final int error = 1;
  static final int STRICT = 3;
  static final int NODE = 5;
  static final int COMMA = 11;
  static final int D_EDGE_OP = 9;
  static final int RBR = 15;
  static final int ID = 18;
  static final int RCUR = 13;
  static final int LCUR = 12;
  static final int SUBGRAPH = 7;
  static final int LBR = 14;
  static final int DIGRAPH = 4;

  /* non terminals */
  static final int graph_type = 18;
  static final int attr_set = 8;
  static final int node_id = 20;
  static final int $START = 0;
  static final int stmt1 = 12;
  static final int opt_attr_list = 7;
  static final int node_stmt = 14;
  static final int stmt_list1 = 10;
  static final int stmt_list = 9;
  static final int edgeOP = 19;
  static final int attr_stmt = 13;
  static final int stmt = 11;
  static final int attr_class = 2;
  static final int edgeRHS = 16;
  static final int NT$8 = 29;
  static final int NT$7 = 28;
  static final int NT$6 = 27;
  static final int NT$5 = 26;
  static final int inside_attr_list = 3;
  static final int NT$4 = 25;
  static final int NT$3 = 24;
  static final int NT$2 = 23;
  static final int NT$1 = 22;
  static final int NT$0 = 21;
  static final int edge_stmt = 15;
  static final int rec_attr_list = 6;
  static final int file = 1;
  static final int attr_list = 5;
  static final int optcomma = 4;
  static final int subg_stmt = 17;
};

