JAVACFLAGS = -sourcepath ../../..
ImList.class: ImList.java
	javac $(JAVACFLAGS) ImList.java

SmallIntSet.class: SmallIntSet.java Makefile
	javac -sourcepath /proj/lang/coins/BackEnd/src SmallIntSet.java
